#!/usr/bin/env bash
# tracker-status-update.sh — generated by user-story-mapping skill (snapshot refinement 2026-06-08)
# Summary: create the 4 new F-SCIM stories with story-points + sprint; apply the approved Breach-1
#          cuts; set the burn-down fields (points + sprint + status) on the refined set so the
#          tracker's NATIVE burn-down reflects the new plan.
# A tracker is the system of record here, so the plan is NOT emitted as local backlog.csv / storymap.csv —
# it lives in the tracker via the field writes below.
# REVIEW each line before running. Opt-in; nothing executes automatically. To revert, use the tracker audit log.

# --- New "Provision tenant users" activity: F-SCIM-01..04 created with points + sprint (the burn-down's work + time axes) ---
jira issue create --project TIMEBOARD --type Story --summary "Provision tenant users via SCIM 2.0 endpoint" \
  --field "Story Points=8"  --field "Sprint=PI-1 (Wk7-12)" --label "persona:enterprise-it-admin"   # F-SCIM-01
jira issue create --project TIMEBOARD --type Story --summary "Map SCIM groups to TimeBoard roles" \
  --field "Story Points=5"  --field "Sprint=PI-1 (Wk7-12)"                                          # F-SCIM-02
jira issue create --project TIMEBOARD --type Story --summary "De-provision on tenant offboarding (SCIM delete)" \
  --field "Story Points=5"  --field "Sprint=PI-1 (Wk7-12)"                                          # F-SCIM-03
jira issue create --project TIMEBOARD --type Story --summary "SCIM bulk-sync + error reporting" \
  --field "Story Points=13" --field "Sprint=PI-2"                                                   # F-SCIM-04 (deferred per Breach 1, Option E)

# --- Existing items cut to make room (Breach 1, Option E) — status field drives the burn-down down ---
jira issue transition S006 "Won't Do"
jira issue transition S007 "Won't Do"
jira issue transition S012 "Won't Do"
jira issue transition S015 "Won't Do"

# To revert a transition: jira issue transition <ID> <prior-state>, or restore via the tracker audit log.
